# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 13 Jul 2012 03:30:09 +0000
*               @ALL          1
*               @user         8
