<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tdem
 * Date: Mon, 15 Apr 2013 04:44:49 +0000
 */

$conf['title'] = 'Wikiproa';
$conf['template'] = 'modified';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
