<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tdem
 * Date: Sat, 21 Jul 2012 09:58:37 +0000
 */

$conf['title'] = 'Wikiproa';
$conf['template'] = 'modified';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
